# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ёкарный бабай 
email: lucius.gu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ёкарный бабай. Записки о разном от Гурова Павла, программиста, 
  который не пишет магического кода.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gurov.github.io" # the base hostname & protocol for your site
twitter_username: gurovpavel
github_username:  gurov

# Build settings
markdown: kramdown

JEKYLL_ENV: production